# Generated by Django 6.1.1 on 2026-09-16 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heat_date', models.DateField(blank=True, null=True)),
                ('mating_date', models.DateField(blank=True, null=True)),
                ('mating_method', models.CharField(choices=[('NATURAL', 'Natural'), ('AI', 'Artificial Insemination')], default='NATURAL', max_length=20)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('pregnancy_status', models.CharField(choices=[('UNKNOWN', 'Unknown / Not confirmed'), ('CONFIRMED', 'Confirmed Pregnant'), ('NOT_PREGNANT', 'Not Pregnant'), ('DELIVERED', 'Delivered'), ('ABORTED', 'Aborted')], default='UNKNOWN', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='farms.farm')),
                ('female_animal', models.ForeignKey(limit_choices_to={'gender': 'FEMALE'}, on_delete=django.db.models.deletion.CASCADE, related_name='breeding_records_as_female', to='animals.animal')),
                ('male_animal', models.ForeignKey(blank=True, limit_choices_to={'gender': 'MALE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breeding_records_as_male', to='animals.animal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-mating_date'],
            },
        ),
        migrations.CreateModel(
            name='KiddingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kidding_date', models.DateField()),
                ('number_of_kids', models.PositiveSmallIntegerField(default=0)),
                ('male_kids', models.PositiveSmallIntegerField(default=0)),
                ('female_kids', models.PositiveSmallIntegerField(default=0)),
                ('birth_assistance', models.CharField(choices=[('NONE', 'None'), ('ASSISTED', 'Assisted'), ('VET_ASSISTED', 'Vet Assisted')], default='NONE', max_length=20)),
                ('complication', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('breeding_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kidding_records', to='breeding.breedingrecord')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='farms.farm')),
                ('female_animal', models.ForeignKey(limit_choices_to={'gender': 'FEMALE'}, on_delete=django.db.models.deletion.CASCADE, related_name='kidding_records', to='animals.animal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-kidding_date'],
            },
        ),
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag_no', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('birth_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('animal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kid_record', to='animals.animal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='farms.farm')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('kidding_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kids', to='breeding.kiddingrecord')),
            ],
            options={
                'ordering': ['tag_no'],
            },
        ),
        migrations.AddIndex(
            model_name='breedingrecord',
            index=models.Index(fields=['farm', 'pregnancy_status'], name='breeding_br_farm_id_4bf2e9_idx'),
        ),
    ]
