# Generated by Django 6.1.1 on 2026-09-16 10:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'species',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag_no', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'Male / Buck'), ('FEMALE', 'Female / Doe')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('birth_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('current_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('source', models.CharField(choices=[('BORN_ON_FARM', 'Born on farm'), ('PURCHASED', 'Purchased')], default='BORN_ON_FARM', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PREGNANT', 'Pregnant'), ('SICK', 'Sick'), ('QUARANTINE', 'Quarantine'), ('SOLD', 'Sold'), ('DEAD', 'Dead'), ('CULLED', 'Culled')], default='ACTIVE', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='animal_photos/')),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='farms.farm')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_as_father', to='animals.animal')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='farms.location')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_as_mother', to='animals.animal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='animals.breed')),
            ],
            options={
                'ordering': ['tag_no'],
            },
        ),
        migrations.CreateModel(
            name='AnimalMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='animals.animal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='farms.farm')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='farms.location')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='farms.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-movement_date'],
            },
        ),
        migrations.AddField(
            model_name='breed',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breeds', to='animals.species'),
        ),
        migrations.CreateModel(
            name='AnimalWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight_date', models.DateField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('weight_method', models.CharField(choices=[('SCALE', 'Weighing Scale'), ('TAPE', 'Girth Tape'), ('ESTIMATED', 'Estimated')], default='SCALE', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to='animals.animal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='farms.farm')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-weight_date'],
                'indexes': [models.Index(fields=['animal', 'weight_date'], name='animals_ani_animal__eb2cdf_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['farm', 'status'], name='animals_ani_farm_id_f9fe7f_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['farm', 'gender'], name='animals_ani_farm_id_e2c92b_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['farm', 'tag_no'], name='animals_ani_farm_id_1526e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='animal',
            constraint=models.UniqueConstraint(fields=('farm', 'tag_no'), name='unique_tag_no_per_farm'),
        ),
        migrations.AlterUniqueTogether(
            name='breed',
            unique_together={('species', 'name')},
        ),
    ]
